#!/usr/bin/env python3
import sys, re
msg_file = sys.argv[1]
with open(msg_file, "r") as f: msg = f.read().strip()
pattern = r"^(feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert)(?:\(.+\))?: .{1,72}$"
if not re.match(pattern, msg):
    print("\n[ERR] Format commit salah. Gunakan: type: description")
    sys.exit(1)