#!/usr/bin/env python3
import sys, subprocess

msg_file = sys.argv[1]
diff_files = subprocess.check_output(['git', 'diff', '--cached', '--name-only']).decode().strip().split('\n')
if diff_files == ['']: diff_files = []
files = ", ".join(diff_files)
draft = f"feat: update {files}\n\n"

with open(msg_file, "r+") as f:
    content = f.read()
    if not content:
        f.seek(0, 0)
        f.write(draft + content)
